version: '3'

services:

  postgres:
    image: 'postgres:13.4'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aecit
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/